### ISSUE TITLE
Synapse - error while parsing a quoted scalar

### ISSUE THREAD

**Issue by Woitekku** [element-hq/ess-starter-edition-core#16]
**Describe the bug**
I'm trying to install Element Starter on AWS EKS. The synapse is giving me following error referencing to ansible:
```
 Message:               An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'yaml.scanner.ScannerError'>, original message: while parsing a quoted scalar
  in "<unicode string>", line 6, column 22
found invalid Unicode character escape code
  in "<unicode string>", line 6, column 26. while parsing a quoted scalar
  in "<unicode string>", line 6, column 22
found invalid Unicode character escape code
  in "<unicode string>", line 6, column 26
```

**To Reproduce**
Have updater and operator up and running + secrets, then apply the deployment.yaml

```
apiVersion: matrix.element.io/v1alpha2
kind: ElementDeployment
metadata:
  name: first-element
  namespace: element-onprem
spec:
  global:
    k8s:
      ingresses:
        ingressClassName: alb
        annotations: {}
        tls:
          mode: external
        services:
          type: ClusterIP
      storage:
        storageClassName: gp3
    secretName: global
    config:
      genericSharedSecretSecretKey: genericSharedSecret
      domainName: chat.xxx
  components:
    elementWeb:
      secretName: element-web
      k8s:
        ingress:
          fqdn: element.chat.xxx
          tls:
            mode: external
        workloads:
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
    synapse:
      secretName: synapse
      config:
        media:
          volume:
            size: 100Gi
        postgresql:
          host:xxx
          user: synapse
          database: synapse
          passwordSecretKey: pgpassword
          sslMode: require
      k8s:
        haproxy:
          workloads:
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
        ingress:
          fqdn: matrix.chat.xxx
          tls:
            mode: external
        redis:
          workloads:
            resources:
              limits:
                memory: 50Mi
              requests:
                cpu: 50m
                memory: 50Mi
        synapse:
          workloads:
            resources:
              limits:
                memory: 4Gi
              requests:
                cpu: 100m
                memory: 100Mi
    wellKnownDelegation:
      secretName: well-known-delegation
      k8s:
        ingress:
          tls:
            mode: external
```

**Expected behavior**
No errors, Synapse pods to be created.
